version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
